### PR TITLE
Add a MARK example for OpenSSL EVP

### PR DESCRIPTION
**Pull request by fwendland**
This PR will add: 
- an OpenSSL encryption/decryption example using AES256 in CBC mode from [DaniloVlad/OpenSSL-AES](https://github.com/DaniloVlad/OpenSSL-AES)
- corresponding MARK entities and rules to verify the use of OpenSSL EVP

This currently does not work. `EVP_CIPHER_CTX` and `EVP_Encrypt*` are seperated into two entities. The resulting order rule defines two entities in the `using` clause. This isn't supported.

### CODE REVIEW

**Comment by oxisto** [comment]
Why did you separate it into two different entities? Isn't it the same CTX object that is being called by `EVP_EncryptInit`, which is also created by `EVP_CIPHER_CTX_new`?

I would suggest adding smaller test files that actually focus on the different variations of calls instead of including a giant openssl example project.

**Comment by JulianSchuette** [comment]
The simplified OpenSSL test works out of the box with WPDS has been included in the PR (#31 ) : 3285f1c52c8aa6f3be9138c8525fc98e7382cdec

For the full example, I will investigate what would be needed to support it and add it to the internal write-up.

**Comment by fwendland** [comment]
Do we still want to include the full example or do we just keep the simple example from Julian?

**Comment by fwendland** [comment]
We will rework this PR.

**Pull request closed without merging**
