### PR TITLE
Major Cleanup (DB/Caching)

### PR DESCRIPTION
**Pull request by oxisto**
- Removing ehcache (for now) since its reflection dark magic is annoying on Java 11+. I will try parsing a larger code base from the benchmarks repo to see whether we run into any problems using simple maps for caching.
- Removed unused test files
- Refactored database connection to remove the singleton concept. This way, we can actually configure the database with the `ServerConfiguration`, for example to disable overflow, i.e. for unit tests or if you are sure that the graph will fit in memory
- Some more general cleanup, organized imports, etc.

### CODE REVIEW

**Comment by oxisto** [comment]
Ok the database connection in codyze is a complete mess. It is impossible to configure the overflow DB from the analysis server because of the singleton pattern. Maybe I will try to tackle a re-write of this later.

**Review by fwendland — CHANGES_REQUESTED** [review]
We should keep `src/test/resources/unittests/qrc_bitcoin.cpp`. It is still used in `src/test/java/de/fraunhofer/aisec/crymlin/OGMTest.java#L307` though the test is disabled for performance reasons.

**Comment by oxisto** [comment]
> We should keep `src/test/resources/unittests/qrc_bitcoin.cpp`. It is still used in `src/test/java/de/fraunhofer/aisec/crymlin/OGMTest.java#L307` though the test is disabled for performance reasons.

Wouldn't it make more sense to have a dedicated script for that in the `scripts` folder that downloads the file - instead of having a 120k LoC test file in a repo that maybe has 10k LoC?

**Comment by fwendland** [comment]
Yes, would make more sense. Can you create a draft?

**Comment by oxisto** [comment]
> Yes, would make more sense. Can you create a draft?

Ok, yes sure.

**Comment by fwendland** [comment]
After taking another look at `qrc_bitcoin.cpp`, I cannot reproduce its pupose. It consists of a large array of binary data for images. 

I would be in favor of removing the test file and the test case, where it's used.

**Review by fwendland — APPROVED** [review]

**Pull request merged**
